@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Aug 24 23:30:04 -0400 2025
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 000fb6f5bc5c405d9afacc9d019e4b7b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_lvl_logic_behav xil_defaultlib.tb_lvl_logic -log elaborate.log"
call xelab  -wto 000fb6f5bc5c405d9afacc9d019e4b7b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_lvl_logic_behav xil_defaultlib.tb_lvl_logic -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
